language: node_js

node_js:
    - "node"
    - "8"
    - "7"

sudo: false

git:
    submodules: false

before_script:
    - npm install

script:
    - npm run test
    - npm run report

# after_success:
#     - npm run report-coveralls
#     - npm run report-codecov
