version: "3"
services:
  node_latest:
    build:
      context: .
      dockerfile: docker/Dockerfile-node-latest
    volumes:
      - ./:/app/
      - /app/node_modules/
  
  node_8:
    build:
      context: .
      dockerfile: docker/Dockerfile-node-8
    volumes:
      - ./:/app/
      - /app/node_modules/
  
  
  node_8_alpine:
    build:
      context: .
      dockerfile: docker/Dockerfile-node-8-alpine
    volumes:
      - ./:/app/
      - /app/node_modules/
  
  node_7_alpine:
    build:
      context: .
      dockerfile: docker/Dockerfile-node-7-alpine
    volumes:
      - ./:/app/
      - /app/node_modules/
  
  node_6_alpine:
    build:
      context: .
      dockerfile: docker/Dockerfile-node-6-alpine
    volumes:
      - ./:/app/
      - /app/node_modules/
  
